CREATE DATABASE `foreign_admission` /*!40100 DEFAULT CHARACTER SET latin1 */

CREATE TABLE `details` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(220) NOT NULL,
 `phno` varchar(12) NOT NULL,
 `address` varchar(500) NOT NULL,
 `gender` varchar(12) NOT NULL,
 `dob` varchar(220) NOT NULL,
 `citizenship` varchar(50) NOT NULL,
 `email` varchar(50) NOT NULL,
 `p1name` varchar(220) DEFAULT NULL,
 `p1address` varchar(500) DEFAULT NULL,
 `p1email` varchar(50) DEFAULT NULL,
 `p1citizenship` varchar(50) DEFAULT NULL,
 `p2name` varchar(220) DEFAULT NULL,
 `p2address` varchar(500) DEFAULT NULL,
 `p2email` varchar(50) DEFAULT NULL,
 `p2citizenship` varchar(50) DEFAULT NULL,
 `schoolname` varchar(500) DEFAULT NULL,
 `schooladdress` varchar(500) DEFAULT NULL,
 `schoolentrydate` varchar(220) DEFAULT NULL,
 `schoolexitdate` varchar(220) DEFAULT NULL,
 `nameschoolofficial` varchar(500) DEFAULT NULL,
 `emailschoolofficial` varchar(50) DEFAULT NULL,
 `preforder1` tinyint(1) DEFAULT NULL,
 `preforder2` tinyint(1) DEFAULT NULL,
 `preforder3` tinyint(1) DEFAULT NULL,
 `test1` varchar(220) DEFAULT NULL,
 `subject1` varchar(220) DEFAULT NULL,
 `score1` varchar(50) DEFAULT NULL,
 `test2` varchar(220) DEFAULT NULL,
 `subject2` varchar(220) DEFAULT NULL,
 `score2` varchar(50) DEFAULT NULL,
 `test3` varchar(220) DEFAULT NULL,
 `subject3` varchar(220) DEFAULT NULL,
 `score3` varchar(50) DEFAULT NULL,
 `test4` varchar(220) DEFAULT NULL,
 `subject4` varchar(220) DEFAULT NULL,
 `score4` varchar(50) DEFAULT NULL,
 `test5` varchar(220) DEFAULT NULL,
 `subject5` varchar(220) DEFAULT NULL,
 `score5` varchar(50) DEFAULT NULL,
 `awards` longtext,
 `activities` longtext,
 `lorname1` varchar(220) DEFAULT NULL,
 `loremail1` varchar(50) DEFAULT NULL,
 `lorname2` varchar(220) DEFAULT NULL,
 `loremail2` varchar(50) DEFAULT NULL,
 `essay` longtext,
 `pic` varchar(500) DEFAULT NULL,
 `sign` varchar(500) DEFAULT NULL,
 `dobproof` varchar(500) DEFAULT NULL,
 `hstranscript` varchar(500) DEFAULT NULL,
 `testscorepdf` varchar(500) DEFAULT NULL,
 `lorpdf` varchar(500) DEFAULT NULL,
 `passportvisapdf` varchar(500) DEFAULT NULL,
 `paymentreceiptpdf` varchar(500) DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1